
# Render dynamic port binding
server.port=${PORT:8080}
# Give the database a permanent home so data doesn't vanish on restart
spring.datasource.url=jdbc:h2:file:./data/regulationsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Enable the H2 Console so you can run your SELECT queries
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Tells Hibernate to create the tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
